[project]
name = "promptdrifter-scripts"
version = "0.1.0"
readme = "pypi-readme.md"
requires-python = ">=3.13"
dependencies = [
    "tomlkit>=0.12.0,<1.0.0"
]

[project.scripts]
update-pr-version = "update_pr_version:main"
